version: "3"

services:
  api:
    build: .
    command: gunicorn wsgi:application --chdir=/technical-resource-db/technical_resource_db_py -b=0.0.0.0:8000 -w=4 -t=10
    container_name: "Technical-Resource-Db-Backend"
    environment:
      TECHNICAL_RESOURCE_DB: ${TECHNICAL_RESOURCE_DB:-development}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: technical-resource-db:backend
    ports:
      - "38383:8000"
    restart: always
    volumes:
      - .:/technical-resource-db
